import java.util.Random;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;


public class Gooey extends javax.swing.JFrame {

    //Instance variables for a bunch of stuff
    static ArrayList<String> mainList, r1, r2, r3, r4, r5, r6, r7, deck, face;
    static ArrayList<Integer> values1, values2, values3, values4, values5, values6, values7, deckValues;
    static ListsOnLists lists;
    static Random gen;
    static ArrayList<JButton> btns;
    static int deckCount, faceValue, deckNum, score;
    static JButton[][] temps;
    
    /**
     * Creates new form Gooey
     */
    public Gooey() {
        btns = new ArrayList<JButton>();
        initComponents();
        lists = new ListsOnLists();
        gen = new Random();
        mainList = new ArrayList<String>();
        r1 = new ArrayList<String>();
        r2 = new ArrayList<String>();
        r3 = new ArrayList<String>();
        r4 = new ArrayList<String>();
        r5 = new ArrayList<String>();
        r6 = new ArrayList<String>();
        r7 = new ArrayList<String>();
        deck = new ArrayList<String>();
        face = new ArrayList<String>();
        values1 = new ArrayList<Integer>();
        values2 = new ArrayList<Integer>();
        values3 = new ArrayList<Integer>();
        values4 = new ArrayList<Integer>();
        values5 = new ArrayList<Integer>();
        values6 = new ArrayList<Integer>();
        values7 = new ArrayList<Integer>();
        deckValues = new ArrayList<Integer>();
        deckCount = 0;
        faceValue = 0;
        deckNum = 16;
        score = 0;
        temps = new JButton[5][7];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        r1c5 = new javax.swing.JButton();
        r1c4 = new javax.swing.JButton();
        r1c3 = new javax.swing.JButton();
        r1c2 = new javax.swing.JButton();
        r1c1 = new javax.swing.JButton();
        r2c3 = new javax.swing.JButton();
        r2c4 = new javax.swing.JButton();
        r2c5 = new javax.swing.JButton();
        r2c1 = new javax.swing.JButton();
        r2c2 = new javax.swing.JButton();
        r3c4 = new javax.swing.JButton();
        r3c3 = new javax.swing.JButton();
        r3c1 = new javax.swing.JButton();
        r3c2 = new javax.swing.JButton();
        r3c5 = new javax.swing.JButton();
        r4c4 = new javax.swing.JButton();
        r4c3 = new javax.swing.JButton();
        r4c1 = new javax.swing.JButton();
        r4c2 = new javax.swing.JButton();
        r4c5 = new javax.swing.JButton();
        r5c4 = new javax.swing.JButton();
        r5c3 = new javax.swing.JButton();
        r5c1 = new javax.swing.JButton();
        r5c2 = new javax.swing.JButton();
        r6c3 = new javax.swing.JButton();
        r6c4 = new javax.swing.JButton();
        r6c1 = new javax.swing.JButton();
        r6c2 = new javax.swing.JButton();
        r6c5 = new javax.swing.JButton();
        r7c3 = new javax.swing.JButton();
        r7c4 = new javax.swing.JButton();
        r7c1 = new javax.swing.JButton();
        r7c2 = new javax.swing.JButton();
        r7c5 = new javax.swing.JButton();
        deckButton = new javax.swing.JButton();
        faceButton = new javax.swing.JButton();
        r5c5 = new javax.swing.JButton();
        deckLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1057, 737));

        r1c5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r1c5.setBorderPainted(false);
        r1c5.setEnabled(false);
        r1c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1c5ActionPerformed(evt);
            }
        });

        r1c4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r1c4.setBorderPainted(false);
        r1c4.setEnabled(false);
        r1c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1c4ActionPerformed(evt);
            }
        });

        r1c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r1c3.setBorderPainted(false);
        r1c3.setEnabled(false);
        r1c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1c3ActionPerformed(evt);
            }
        });

        r1c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r1c2.setBorderPainted(false);
        r1c2.setEnabled(false);
        r1c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1c2ActionPerformed(evt);
            }
        });

        r1c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r1c1.setBorderPainted(false);
        r1c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1c1ActionPerformed(evt);
            }
        });

        r2c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r2c3.setBorderPainted(false);
        r2c3.setEnabled(false);
        r2c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2c3ActionPerformed(evt);
            }
        });

        r2c4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r2c4.setBorderPainted(false);
        r2c4.setEnabled(false);
        r2c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2c4ActionPerformed(evt);
            }
        });

        r2c5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r2c5.setBorderPainted(false);
        r2c5.setEnabled(false);
        r2c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2c5ActionPerformed(evt);
            }
        });

        r2c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r2c1.setBorderPainted(false);
        r2c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2c1ActionPerformed(evt);
            }
        });

        r2c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r2c2.setBorderPainted(false);
        r2c2.setEnabled(false);
        r2c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2c2ActionPerformed(evt);
            }
        });

        r3c4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r3c4.setBorderPainted(false);
        r3c4.setEnabled(false);
        r3c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3c4ActionPerformed(evt);
            }
        });

        r3c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r3c3.setBorderPainted(false);
        r3c3.setEnabled(false);
        r3c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3c3ActionPerformed(evt);
            }
        });

        r3c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r3c1.setBorderPainted(false);
        r3c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3c1ActionPerformed(evt);
            }
        });

        r3c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r3c2.setBorderPainted(false);
        r3c2.setEnabled(false);
        r3c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3c2ActionPerformed(evt);
            }
        });

        r3c5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r3c5.setBorderPainted(false);
        r3c5.setEnabled(false);
        r3c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3c5ActionPerformed(evt);
            }
        });

        r4c4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r4c4.setBorderPainted(false);
        r4c4.setEnabled(false);
        r4c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4c4ActionPerformed(evt);
            }
        });

        r4c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r4c3.setBorderPainted(false);
        r4c3.setEnabled(false);
        r4c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4c3ActionPerformed(evt);
            }
        });

        r4c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r4c1.setBorderPainted(false);
        r4c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4c1ActionPerformed(evt);
            }
        });

        r4c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r4c2.setBorderPainted(false);
        r4c2.setEnabled(false);
        r4c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4c2ActionPerformed(evt);
            }
        });

        r4c5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r4c5.setBorderPainted(false);
        r4c5.setEnabled(false);
        r4c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4c5ActionPerformed(evt);
            }
        });

        r5c4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r5c4.setBorderPainted(false);
        r5c4.setEnabled(false);
        r5c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5c4ActionPerformed(evt);
            }
        });

        r5c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r5c3.setBorderPainted(false);
        r5c3.setEnabled(false);
        r5c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5c3ActionPerformed(evt);
            }
        });

        r5c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r5c1.setBorderPainted(false);
        r5c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5c1ActionPerformed(evt);
            }
        });

        r5c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r5c2.setBorderPainted(false);
        r5c2.setEnabled(false);
        r5c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5c2ActionPerformed(evt);
            }
        });

        r6c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r6c3.setBorderPainted(false);
        r6c3.setEnabled(false);
        r6c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6c3ActionPerformed(evt);
            }
        });

        r6c4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r6c4.setBorderPainted(false);
        r6c4.setEnabled(false);
        r6c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6c4ActionPerformed(evt);
            }
        });

        r6c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r6c1.setBorderPainted(false);
        r6c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6c1ActionPerformed(evt);
            }
        });

        r6c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r6c2.setBorderPainted(false);
        r6c2.setEnabled(false);
        r6c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6c2ActionPerformed(evt);
            }
        });

        r6c5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r6c5.setBorderPainted(false);
        r6c5.setEnabled(false);
        r6c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6c5ActionPerformed(evt);
            }
        });

        r7c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r7c3.setBorderPainted(false);
        r7c3.setEnabled(false);
        r7c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7c3ActionPerformed(evt);
            }
        });

        r7c4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r7c4.setBorderPainted(false);
        r7c4.setEnabled(false);
        r7c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7c4ActionPerformed(evt);
            }
        });

        r7c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r7c1.setBorderPainted(false);
        r7c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7c1ActionPerformed(evt);
            }
        });

        r7c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r7c2.setBorderPainted(false);
        r7c2.setEnabled(false);
        r7c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7c2ActionPerformed(evt);
            }
        });

        r7c5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r7c5.setBorderPainted(false);
        r7c5.setEnabled(false);
        r7c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7c5ActionPerformed(evt);
            }
        });

        deckButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        deckButton.setBorderPainted(false);
        deckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deckButtonActionPerformed(evt);
            }
        });

        faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        faceButton.setBorderPainted(false);
        faceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faceButtonActionPerformed(evt);
            }
        });

        r5c5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        r5c5.setBorderPainted(false);
        r5c5.setEnabled(false);
        r5c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5c5ActionPerformed(evt);
            }
        });

        deckLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        scoreLabel.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        scoreLabel.setText("Score: ");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(71, 71, 71)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(r1c1)
                            .add(r1c2)
                            .add(r1c3)
                            .add(r1c4)
                            .add(r1c5))
                        .add(51, 51, 51)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(r2c1)
                            .add(r2c2)
                            .add(r2c3)
                            .add(r2c4)
                            .add(r2c5)))
                    .add(scoreLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(51, 51, 51)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(r3c1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(r3c2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(r3c3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(r3c4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(r3c5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(deckButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(deckLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(51, 51, 51)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(r4c1)
                    .add(r4c2)
                    .add(r4c3)
                    .add(r4c4)
                    .add(r4c5))
                .add(51, 51, 51)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(r5c1)
                            .add(r5c2)
                            .add(r5c3)
                            .add(r5c4)
                            .add(r5c5))
                        .add(51, 51, 51)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(r6c1)
                            .add(r6c2)
                            .add(r6c3)
                            .add(r6c4)
                            .add(r6c5))
                        .add(51, 51, 51)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(r7c1)
                            .add(r7c2)
                            .add(r7c3)
                            .add(r7c4)
                            .add(r7c5)))
                    .add(faceButton))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(r7c5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r7c4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r7c3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r7c2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r7c1))
                    .add(layout.createSequentialGroup()
                        .add(r6c5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r6c4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r6c3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r6c2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r6c1))
                    .add(layout.createSequentialGroup()
                        .add(r5c5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r5c4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r5c3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r5c2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r5c1))
                    .add(layout.createSequentialGroup()
                        .add(r4c5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r4c4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r4c3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r4c2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r4c1))
                    .add(layout.createSequentialGroup()
                        .add(r3c5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r3c4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r3c3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r3c2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r3c1))
                    .add(layout.createSequentialGroup()
                        .add(r2c5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r2c4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r2c3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r2c2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r2c1))
                    .add(layout.createSequentialGroup()
                        .add(r1c5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r1c4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r1c3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r1c2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(r1c1)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 32, Short.MAX_VALUE)
                .add(deckLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(deckButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(faceButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(scoreLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deckButtonActionPerformed
        /*
         * Sets the faceBtton to the top card in the deck
         * Increments the value of the faceButton
         * Decrements the number of cards in the deck
         * Updates the deckLabel and Score
         */
        faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + deck.get(deckCount) + ".png")));
        faceValue = deckValues.get(deckCount);
        deckCount++;
        deckNum--;
        deckLabel.setText(Integer.toString(deckNum));
        score -= 10;
        scoreLabel.setText("Score: " + Integer.toString(score));
        
        //Disables the deck when it runs out of cards
        if(deckCount == 15){
            deckButton.setEnabled(false);
            deckLabel.setVisible(false);
        }
    }//GEN-LAST:event_deckButtonActionPerformed

    //NEVER ACTUALLY CALLED
    private void faceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faceButtonActionPerformed
        
    }//GEN-LAST:event_faceButtonActionPerformed

    private void r1c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1c1ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values1.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r1.get(0) + ".png")));
            faceValue = values1.get(0);
            values1.remove(0);
            r1c1.setVisible(false);
            r1c2.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r1c1ActionPerformed

    private void r1c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1c2ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values1.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r1.get(1) + ".png")));
            faceValue = values1.get(0);
            values1.remove(0);
            r1c2.setVisible(false);
            r1c3.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r1c2ActionPerformed

    private void r1c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1c3ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values1.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r1.get(2) + ".png")));
            faceValue = values1.get(0);
            values1.remove(0);
            r1c3.setVisible(false);
            r1c4.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r1c3ActionPerformed

    private void r1c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1c4ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values1.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r1.get(3) + ".png")));
            faceValue = values1.get(0);
            values1.remove(0);
            r1c4.setVisible(false);
            r1c5.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r1c4ActionPerformed

    private void r1c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1c5ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible 
         * Updates the score
         */
        int num = values1.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r1.get(4) + ".png")));
            faceValue = values1.get(0);
            values1.remove(0);
            r1c5.setVisible(false);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r1c5ActionPerformed

    private void r2c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2c1ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values2.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r2.get(0) + ".png")));
            faceValue = values2.get(0);
            values2.remove(0);
            r2c1.setVisible(false);
            r2c2.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r2c1ActionPerformed

    private void r2c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2c2ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values2.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r2.get(1) + ".png")));
            faceValue = values2.get(0);
            values2.remove(0);
            r2c2.setVisible(false);
            r2c3.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r2c2ActionPerformed

    private void r2c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2c3ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values2.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r2.get(2) + ".png")));
            faceValue = values2.get(0);
            values2.remove(0);
            r2c3.setVisible(false);
            r2c4.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r2c3ActionPerformed

    private void r2c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2c4ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values2.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r2.get(3) + ".png")));
            faceValue = values2.get(0);
            values2.remove(0);
            r2c4.setVisible(false);
            r2c5.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r2c4ActionPerformed

    private void r2c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2c5ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible
         * Updates the score
         */
        int num = values2.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r2.get(4) + ".png")));
            faceValue = values2.get(0);
            values2.remove(0);
            r2c5.setVisible(false);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r2c5ActionPerformed

    private void r3c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3c1ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values3.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r3.get(0) + ".png")));
            faceValue = values3.get(0);
            values3.remove(0);
            r3c1.setVisible(false);
            r3c2.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r3c1ActionPerformed

    private void r3c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3c2ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values3.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r3.get(1) + ".png")));
            faceValue = values3.get(0);
            values3.remove(0);
            r3c2.setVisible(false);
            r3c3.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r3c2ActionPerformed

    private void r3c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3c3ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values3.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r3.get(2) + ".png")));
            faceValue = values3.get(0);
            values3.remove(0);
            r3c3.setVisible(false);
            r3c4.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r3c3ActionPerformed

    private void r3c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3c4ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values3.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r3.get(3) + ".png")));
            faceValue = values3.get(0);
            values3.remove(0);
            r3c4.setVisible(false);
            r3c5.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r3c4ActionPerformed

    private void r3c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3c5ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible
         * Updates the score
         */
        int num = values3.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r3.get(4) + ".png")));
            faceValue = values3.get(0);
            values3.remove(0);
            r3c5.setVisible(false);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r3c5ActionPerformed

    private void r4c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4c1ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values4.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r4.get(0) + ".png")));
            faceValue = values4.get(0);
            values4.remove(0);
            r4c1.setVisible(false);
            r4c2.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r4c1ActionPerformed

    private void r4c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4c2ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values4.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r4.get(1) + ".png")));
            faceValue = values4.get(0);
            values4.remove(0);
            r4c2.setVisible(false);
            r4c3.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r4c2ActionPerformed

    private void r4c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4c3ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values4.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r4.get(2) + ".png")));
            faceValue = values4.get(0);
            values4.remove(0);
            r4c3.setVisible(false);
            r4c4.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r4c3ActionPerformed

    private void r4c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4c4ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values4.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r4.get(3) + ".png")));
            faceValue = values4.get(0);
            values4.remove(0);
            r4c4.setVisible(false);
            r4c5.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r4c4ActionPerformed

    private void r4c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4c5ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible
         * Updates the score
         */
        int num = values4.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r4.get(4) + ".png")));
            faceValue = values4.get(0);
            values4.remove(0);
            r4c5.setVisible(false);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r4c5ActionPerformed

    private void r5c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5c1ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values5.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r5.get(0) + ".png")));
            faceValue = values5.get(0);
            values5.remove(0);
            r5c1.setVisible(false);
            r5c2.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r5c1ActionPerformed

    private void r5c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5c2ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values5.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r5.get(1) + ".png")));
            faceValue = values5.get(0);
            values5.remove(0);
            r5c2.setVisible(false);
            r5c3.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r5c2ActionPerformed

    private void r5c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5c3ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values5.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r5.get(2) + ".png")));
            faceValue = values5.get(0);
            values5.remove(0);
            r5c3.setVisible(false);
            r5c4.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r5c3ActionPerformed

    private void r5c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5c4ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values5.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r5.get(3) + ".png")));
            faceValue = values5.get(0);
            values5.remove(0);
            r5c4.setVisible(false);
            r5c5.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r5c4ActionPerformed

    private void r5c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5c5ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible
         * Updates the score
         */
        int num = values5.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r5.get(4) + ".png")));
            faceValue = values5.get(0);
            values5.remove(0);
            r5c5.setVisible(false);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r5c5ActionPerformed

    private void r6c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6c1ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values6.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r6.get(0) + ".png")));
            faceValue = values6.get(0);
            values6.remove(0);
            r6c1.setVisible(false);
            r6c2.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r6c1ActionPerformed

    private void r6c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6c2ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values6.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r6.get(1) + ".png")));
            faceValue = values6.get(0);
            values6.remove(0);
            r6c2.setVisible(false);
            r6c3.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r6c2ActionPerformed

    private void r6c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6c3ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values6.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r6.get(2) + ".png")));
            faceValue = values6.get(0);
            values6.remove(0);
            r6c3.setVisible(false);
            r6c4.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r6c3ActionPerformed

    private void r6c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6c4ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values6.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r6.get(3) + ".png")));
            faceValue = values6.get(0);
            values6.remove(0);
            r6c4.setVisible(false);
            r6c5.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r6c4ActionPerformed

    private void r6c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6c5ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible
         * Updates the score
         */
        int num = values6.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r6.get(4) + ".png")));
            faceValue = values6.get(0);
            values6.remove(0);
            r6c5.setVisible(false);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r6c5ActionPerformed

    private void r7c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7c1ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values7.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r7.get(0) + ".png")));
            faceValue = values7.get(0);
            values7.remove(0);
            r7c1.setVisible(false);
            r7c2.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r7c1ActionPerformed

    private void r7c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7c2ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values7.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r7.get(1) + ".png")));
            faceValue = values7.get(0);
            values7.remove(0);
            r7c2.setVisible(false);
            r7c3.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r7c2ActionPerformed

    private void r7c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7c3ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values7.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r7.get(2) + ".png")));
            faceValue = values7.get(0);
            values7.remove(0);
            r7c3.setVisible(false);
            r7c4.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r7c3ActionPerformed

    private void r7c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7c4ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible and makes the one behind it visible
         * Updates the score
         */
        int num = values7.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r7.get(3) + ".png")));
            faceValue = values7.get(0);
            values7.remove(0);
            r7c4.setVisible(false);
            r7c5.setEnabled(true);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r7c4ActionPerformed

    private void r7c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7c5ActionPerformed
        /*
         * Checks if the card clicked it +1 or -1 the value of the face card
         * Changes the faceButton icon if it is
         * Makes the card clicked invisible
         * Updates the score
         */
        int num = values7.get(0).intValue();
        if((num == (faceValue + 1) || num == (faceValue - 1)) || (num == (faceValue + 12) || num == (faceValue - 12))){
            faceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/" + r7.get(4) + ".png")));
            faceValue = values7.get(0);
            values7.remove(0);
            r7c5.setVisible(false);
            score += 240;
            scoreLabel.setText("Score: " + Integer.toString(score));
        }
    }//GEN-LAST:event_r7c5ActionPerformed

    private void assignLists(){
        int num;
        int i;
        String tmp;
        
        
        //Randomly assigns cards to the various rows
        
        //Row1
        i = 0;
        while(i <= 4){
            num = gen.nextInt(52);
            if(mainList.get(num) != null){
                r1.add(mainList.get(num));
                tmp = r1.get(i).substring(1);
                if(tmp.charAt(0) == '0'){
                    tmp = tmp.substring(1);
                }
                values1.add(Integer.parseInt(tmp));
                mainList.set(num, null);
                i++;
            }
        }
        
        //Row2
        i = 0;
        while(i <= 4){
            if(mainList.get(num = gen.nextInt(52)) != null){
                r2.add(mainList.get(num));
                tmp = r2.get(i).substring(1);
                if(tmp.charAt(0) == '0'){
                    tmp = tmp.substring(1);
                }
                values2.add(Integer.parseInt(tmp));
                mainList.set(num, null);
                i++;
            }
        }
        
        //Row3
        i = 0;
        while(i <= 4){
            if(mainList.get(num = gen.nextInt(52)) != null){
                r3.add(mainList.get(num));
                tmp = r3.get(i).substring(1);
                if(tmp.charAt(0) == '0'){
                    tmp = tmp.substring(1);
                }
                values3.add(Integer.parseInt(tmp));
                mainList.set(num, null);
                i++;
            }
        }
        
        //Row4
        i = 0;
        while(i <= 4){
            if(mainList.get(num = gen.nextInt(52)) != null){
                r4.add(mainList.get(num));
                tmp = r4.get(i).substring(1);
                if(tmp.charAt(0) == '0'){
                    tmp = tmp.substring(1);
                }
                values4.add(Integer.parseInt(tmp));
                mainList.set(num, null);
                i++;
            }
        }
        
        //Row5
        i = 0;
        while(i <= 4){
            if(mainList.get(num = gen.nextInt(52)) != null){
                r5.add(mainList.get(num));
                tmp = r5.get(i).substring(1);
                if(tmp.charAt(0) == '0'){
                    tmp = tmp.substring(1);
                }
                values5.add(Integer.parseInt(tmp));
                mainList.set(num, null);
                i++;
            }
        }
        
        //Row6
        i = 0;
        while(i <= 4){
            if(mainList.get(num = gen.nextInt(52)) != null){
                r6.add(mainList.get(num));
                tmp = r6.get(i).substring(1);
                if(tmp.charAt(0) == '0'){
                    tmp = tmp.substring(1);
                }
                values6.add(Integer.parseInt(tmp));
                mainList.set(num, null);
                i++;
            }
        }
        
        //Row7
        i = 0;
        while(i <= 4){
            if(mainList.get(num = gen.nextInt(52)) != null){
                r7.add(mainList.get(num));
                tmp = r7.get(i).substring(1);
                if(tmp.charAt(0) == '0'){
                    tmp = tmp.substring(1);
                }
                values7.add(Integer.parseInt(tmp));
                mainList.set(num, null);
                i++;
            }
        }
        
        //Face
        i = 0;
        while(i < 1){
            if(mainList.get(num = gen.nextInt(52)) != null){
                face.add(mainList.get(num));
                tmp = face.get(i).substring(1);
                if(tmp.charAt(0) == '0'){
                    tmp = tmp.substring(1);
                }
                faceValue = Integer.parseInt(tmp);
                mainList.set(num, null);
                i++;
            }
        }
        
        
        //Deck
        i = 0;
        while(i <= 15){
            if(mainList.get(num = gen.nextInt(52)) != null){
                deck.add(mainList.get(num));
                tmp = deck.get(i).substring(1);
                if(tmp.charAt(0) == '0'){
                    tmp = tmp.substring(1);
                }
                deckValues.add(Integer.parseInt(tmp));
                mainList.set(num, null);
                i++;
            }
        }
        
    }
    
    private void createCards(){
        addCardList();
        int j;
        
        //Sets the icons for all the cards on the screen
        
        j = 0;
        for(int i = 0; i <= 4; i++){
            btns.get(i).setIcon(new ImageIcon(getClass().getResource("/resources/" + r1.get(j) + ".png")));
            j++;
        }
        
        j = 0;
        for(int i = 5; i <= 9; i++){
            btns.get(i).setIcon(new ImageIcon(getClass().getResource("/resources/" + r2.get(j) + ".png")));
            j++;
        }
        
        j = 0;
        for(int i = 10; i <= 14; i++){
            btns.get(i).setIcon(new ImageIcon(getClass().getResource("/resources/" + r3.get(j) + ".png")));
            j++;
        }
        
        j = 0;
        for(int i = 15; i <= 19; i++){
            btns.get(i).setIcon(new ImageIcon(getClass().getResource("/resources/" + r4.get(j) + ".png")));
            j++;
        }
        
        j = 0;
        for(int i = 20; i <= 24; i++){
            btns.get(i).setIcon(new ImageIcon(getClass().getResource("/resources/" + r5.get(j) + ".png")));
            j++;
        }
        
        j = 0;
        for(int i = 25; i <= 29; i++){
            btns.get(i).setIcon(new ImageIcon(getClass().getResource("/resources/" + r6.get(j) + ".png")));
            j++;
        }
        
        j = 0;
        for(int i = 30; i <= 34; i++){
            btns.get(i).setIcon(new ImageIcon(getClass().getResource("/resources/" + r7.get(j) + ".png")));
            j++;
        }
        
        faceButton.setIcon(new ImageIcon(getClass().getResource("/resources/" + face.get(0) + ".png")));
       
        deckLabel.setText(Integer.toString(deckNum));
        
        scoreLabel.setText("Score: " + Integer.toString(score));
    }
    
    public void getMainList(){
        //Gets the names of the cards
        mainList = lists.makeList();
        
        //Randomly assigns values
        assignLists();
        
        //Sets the card icons and displays them
        createCards();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gooey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gooey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gooey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gooey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gooey().setVisible(true);
            }
        });
    }
    
    private void addCardList(){
        //Adds all the buttons to an ArrayList
        btns.add(r1c1);
        btns.add(r1c2);
        btns.add(r1c3);
        btns.add(r1c4);
        btns.add(r1c5);
        btns.add(r2c1);
        btns.add(r2c2);
        btns.add(r2c3);
        btns.add(r2c4);
        btns.add(r2c5);
        btns.add(r3c1);
        btns.add(r3c2);
        btns.add(r3c3);
        btns.add(r3c4);
        btns.add(r3c5);
        btns.add(r4c1);
        btns.add(r4c2);
        btns.add(r4c3);
        btns.add(r4c4);
        btns.add(r4c5);
        btns.add(r5c1);
        btns.add(r5c2);
        btns.add(r5c3);
        btns.add(r5c4);
        btns.add(r5c5);
        btns.add(r6c1);
        btns.add(r6c2);
        btns.add(r6c3);
        btns.add(r6c4);
        btns.add(r6c5);
        btns.add(r7c1);
        btns.add(r7c2);
        btns.add(r7c3);
        btns.add(r7c4);
        btns.add(r7c5);
        
        int ct = 0;
        for(int r = 0; r < 5; r++){
            for(int c = 0; c < 7; c++){
                temps[r][c] = btns.get(ct);
                ct++;
            }
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deckButton;
    private javax.swing.JLabel deckLabel;
    private javax.swing.JButton faceButton;
    private javax.swing.JButton r1c1;
    private javax.swing.JButton r1c2;
    private javax.swing.JButton r1c3;
    private javax.swing.JButton r1c4;
    private javax.swing.JButton r1c5;
    private javax.swing.JButton r2c1;
    private javax.swing.JButton r2c2;
    private javax.swing.JButton r2c3;
    private javax.swing.JButton r2c4;
    private javax.swing.JButton r2c5;
    private javax.swing.JButton r3c1;
    private javax.swing.JButton r3c2;
    private javax.swing.JButton r3c3;
    private javax.swing.JButton r3c4;
    private javax.swing.JButton r3c5;
    private javax.swing.JButton r4c1;
    private javax.swing.JButton r4c2;
    private javax.swing.JButton r4c3;
    private javax.swing.JButton r4c4;
    private javax.swing.JButton r4c5;
    private javax.swing.JButton r5c1;
    private javax.swing.JButton r5c2;
    private javax.swing.JButton r5c3;
    private javax.swing.JButton r5c4;
    private javax.swing.JButton r5c5;
    private javax.swing.JButton r6c1;
    private javax.swing.JButton r6c2;
    private javax.swing.JButton r6c3;
    private javax.swing.JButton r6c4;
    private javax.swing.JButton r6c5;
    private javax.swing.JButton r7c1;
    private javax.swing.JButton r7c2;
    private javax.swing.JButton r7c3;
    private javax.swing.JButton r7c4;
    private javax.swing.JButton r7c5;
    private javax.swing.JLabel scoreLabel;
    // End of variables declaration//GEN-END:variables
}
